### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Marcos-Sousa** [ingridkno/consulta_sinapi#1]

**Comment by ingridkno** [comment]
Oi Marcos! Tudo certo? Vi que você fechou o comentário, mas se quiser ainda alguma ajuda me fale. Meu linkedin é esse: https://www.linkedin.com/in/ingrid-knochenhauer/

**Comment by Marcos-Sousa** [comment]
Oii Ingrid, mandei o convite no linkedin.. esperando seu aceite,,
